from typing import Iterable, Protocol
from models.u5_glyph import U5Glyph

class ConsoleService(Protocol):
    
    def print_ascii(self, msg: str | Iterable[int], include_carriage_return: bool = True, no_prompt = False): ...
    def print_runes(self, msg: str | Iterable[int], include_carriage_return: bool = True, no_prompt = False): ...
    def print_glyphs(self, glyphs: Iterable[U5Glyph], include_carriage_return: bool = True, no_prompt = False): ...
