# file: display/display_engine.py
from typing import Protocol

class DisplayService(Protocol):

    def init(self): ...
    def get_fps(self): ...
    def set_window_title(self, window_title: str): ...
    def render(self): ...

