from typing import Protocol
import pygame

from dark_libraries.dark_wave import DarkWave, DarkWaveGenerator, DarkWaveStereo

class SoundService(Protocol):

    def init(self): ...

    #
    # Volume Control
    #

    def set_sfx_volume(self, value: float) -> None: ...
    def get_sfx_volume(self) -> float: ...
    def set_soundtrack_volume(self, value: float) -> None: ...
    def get_soundtrack_volume(self) -> float: ...


    #
    # SFX & SFX Playback
    #

    def get_generator(self) -> DarkWaveGenerator: ...
    def play_sound(self, input_wave: DarkWave | DarkWaveStereo) -> tuple[pygame.mixer.Sound, pygame.mixer.Channel]: ...
    def play_music(self, path): ...
    def stop_music(self): ...
    def fade_music(self): ...
